### ISSUE TITLE
Wrong number of threads

### ISSUE THREAD

**Issue by tigerdgp** [abueide/harry-plotter#48]
Hi, I set 3 threads, but only 2 is used
Version 1.1.8
![Screenshot_164](https://user-images.githubusercontent.com/5365490/119597630-d2e7bf00-bdb7-11eb-96e9-2bbd72ae64ca.png)

**Comment by abueide** [comment]
i can't reproduce this, are you sure you clicked save?

**Comment by konkersgg** [comment]
here too. it wont save threads and K size. Also, where are the logs located? oO

**Comment by cojarbi** [comment]
Are you guys compiling 1.1.8?

**Comment by CDprotector** [comment]
same here, setting threads to 4, save job, start all - Using 2 threads of strippe... Not using saved settings

**Comment by cojarbi** [comment]
I can replicate on 1.1.7

**Comment by konkersgg** [comment]
> Are you guys compiling 1.1.8?

no. using 1.1.6 and 1.1.7 same result.

**Comment by cojarbi** [comment]
Asking because OP wrote 1.1.8

**Comment by abueide** [comment]
@cojarbi what happened was after 1.1.8 had a pretty critical bug i ended up deleting 1.1.7 & 1.1.8 and merging them into a new 1.1.7 prerelease with additional bufixes. sorry for the confusion.

**Comment by abueide** [comment]
fixed in 1.1.7-RC2

**Comment by cojarbi** [comment]
Its still showing the same 2 threads when 4 is selected. Also the % o the jobs panel its back to symbol and not the actual %
